{{- range $roleName, $subjects := .Values.roleBindingsAndSubjects }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-role-binding" $roleName | trunc 63 | trimSuffix "-" }}
  namespace: {{ printf "%s-namespace" $roleName | trunc 63 | trimSuffix "-" }}
subjects:
{{- range $subject := $subjects }}
  - kind: {{ $subject.kind }}
    name: {{ $subject.name }}
    {{- if $subject.namespace }}
    namespace: {{ $subject.namespace }}
    {{- end }}
{{- end }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
